dataset_name: RepCount_pose
train_split: ['train']
test_split: ['test']
dataset: {
  dataset_root_dir: './RepCount_pose',
  csv_label_path: 'all_action.csv',
}
PoseRAC: {
  seed: 42,
  # TODO
  dim: 100, # 99 -> 104
  heads: 10, # 9 (105)-> 8 (104) - >1
  enc_layer: 6,
  all_key_points: 100, # 99-> 109 -> 105 for 5 angels + 100 padding
  learning_rate: 0.001,
  alpha: 0.01
}
Action_trigger: {
  enter_threshold: 0.717, # 0.78  best 0.717
  exit_threshold: 0.30, # best 0.3
  momentum: 0.4
}
trainer: {
  max_epochs: 200,
  auto_lr_find: True,
  accelerator: 'gpu',
  devices: 1
}
save_ckpt_path: 'new_weights_only_5_ave_joints_can_del200epo.pth'
